version: '3'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /home/node/app/node_modules
      - .:/home/node/app

# Para rodar teste será necessário rodar o passo a passo abaixo:
# docker ps e copiar o container id
# docker exect -it docker_id npm run test

# docker-compose -f docker-compose-dev.yml up
# docker-compose -f docker-compose-dev.yml up --build
# docker-compose -f docker-compose-dev.yml down
